name: research
channels:
  - defaults
dependencies:
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.1.1
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cycler=0.10.0
  - freetype=2.10.2
  - idna=2.9
  - intel-openmp=2019.4
  - kiwisolver=1.2.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libpng=1.6.37
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.4
  - pip=20.1.1
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=8.0
  - requests=2.24.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - tornado=6.0.4
  - urllib3=1.25.9
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - wincertstore==0.2
    - wrapt==1.12.1
prefix: /Users/lucas/anaconda2/envs/research

